[project]
name = "ur-geo-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "orjson>=3.10",
  "pydantic>=2.7",
  "pydantic-settings>=2.4",
]

[tool.uvicorn]
factory = false
host = "0.0.0.0"
port = 5178
app = "app.main:app"
